### ISSUE TITLE
incident list -> various modification

### ISSUE THREAD

**Issue by jerolomb** [informed-governance-project/NISINP#100]
**Describe the bug**
To DO : 

- [x] display all the submitted report not only the last one in the regulator view
- [x]  display all the submitted report not only the last one in the operator view
- [x] Initial Assessment and Final report available at the same time. If I click on Final report I get an error message. Final Report should not be clickable before I have send the Initial Assessment 
![image](https://github.com/informed-governance-project/governance-platform/assets/18661517/504ae79c-f584-4f3c-a335-e4a9a7844615)

- [x] Change significative impact when the last submitted report change
- [ ] Add the platform admin a choice to modify the number of allowed incident report submitted

**ILR** how we calculate the significative impact ? 
- One of the report has impacts ticked ? 
- the last report  ?
- when the significative impact is set can we unset it as operator by changing the report  ?

**ILR** should we restrict the number of report per day ?

**Comment by tochinet** [comment]
- Le fait qu'un incident soit significatif est toujour lié au dernier rapport en effet. 
- Si l'opérateur change l'impact, le critère significatif ou pas sera adapté automatiquement en conséquence .
- Une restriction du nombre de rapports pour des raisons de sécurité est souhaitable, mais la limite peut être assez élevée, par exemple 20 par utilisateur. Le mieux serait de permettre au platform admin de modifier ce nombre, et de signaler le dépassement à l'utilisateur par un pop-up lorsqu'il essaie de créer "le rapport de trop"

Mais ceci n'est pas lié aux deux TODOs du texte.

Christophe, Pascal ...

**Comment by jerolomb** [comment]
The number of incident can be changed by a sysadmin in conf file
