### ISSUE TITLE
Admin view -> regulators

### ISSUE THREAD

**Issue by jerolomb** [informed-governance-project/NISINP#123]
**Describe the enhancement**

- [x] Put the multilinguism in the relevent field of Regulators
- [x] when creating a new regulator : change the sectors display view to have that 
![image](https://github.com/informed-governance-project/governance-platform/assets/18661517/2d8feb6f-c617-457d-8055-dd32148aedd4)

**Comment by jfrocha** [comment]
fix @https://github.com/informed-governance-project/NISINP/commit/dc99a52958b4fac1f2f1b170fb59e066b1bae47b
