### ISSUE TITLE
Rename CERT into Observer

### ISSUE THREAD

**Issue by jerolomb** [informed-governance-project/NISINP#124]
**Describe the bug**
All the CERT name has to be renamed observer.

Ex : observer user

**Comment by jfrocha** [comment]
Fix 
@https://github.com/informed-governance-project/NISINP/commit/e575bf0c67de76fde3042a8bcbd1357a0795c9c3
@https://github.com/informed-governance-project/NISINP/commit/76a91cc3277cac70bc73c1cce884d9df53079ee0
