### ISSUE TITLE
Regulator administrator -> remove the possibility to create company

### ISSUE THREAD

**Issue by jerolomb** [informed-governance-project/NISINP#130]
**Describe the bug**
Regulator administrator -> remove the possibility to create company

**Comment by tochinet** [comment]
Not clear why it should be removed. But at the moment (issue #131 ) neither RelulatorAdmin nor RegulatorUser can create companies successfully (i.e. with a working set of users).

**Comment by jerolomb** [comment]
Because it was not in the specifications and discussed during last meeting

For the next release (v0.1.5) we have cut the possibility to add user to the company which lead to error

**Comment by tochinet** [comment]
What was done today crates an additional bug as RegulatorUser, click on Company Add gives 

AttributeError at /admin/governanceplatform/company/add/
'BlankChoiceIterator' object has no attribute '__len__'
Request Method:	GET
Request URL:	http://server.domain/admin/governanceplatform/company/add/
Django Version:	5.0.3
Exception Type:	AttributeError
Exception Value:	
'BlankChoiceIterator' object has no attribute '__len__'
Exception Location:	/home/helpdeskske/.cache/pypoetry/virtualenvs/governanceplatform-AGxECetm-py3.10/lib/python3.10/site-packages/django/utils/functional.py, line 188, in __wrapper__
Raised during:	django.contrib.admin.options.add_view
Python Executable:	/usr/bin/python3
Python Version:	3.10.12
Python Path:	
['/home/helpdeskske/NISINP',
 '/home/helpdeskske/.cache/pypoetry/virtualenvs/governanceplatform-AGxECetm-py3.10/lib/python3.10/site-packages',
 '/usr/lib/python310.zip',
 '/usr/lib/python3.10',
 '/usr/lib/python3.10/lib-dynload',
 '/usr/local/lib/python3.10/dist-packages',
 '/usr/lib/python3/dist-packages',
 '/home/helpdeskske/.cache/pypoetry/virtualenvs/governanceplatform-AGxECetm-py3.10/lib/python3.10/site-packages/odf',
 '/home/helpdeskske/.cache/pypoetry/virtualenvs/governanceplatform-AGxECetm-py3.10/lib/python3.10/site-packages/odf',
 '/home/helpdeskske/.cache/pypoetry/virtualenvs/governanceplatform-AGxECetm-py3.10/lib/python3.10/site-packages/odf',
 '/home/helpdeskske/.cache/pypoetry/virtualenvs/governanceplatform-AGxECetm-py3.10/lib/python3.10/site-packages/odf',
 '/home/helpdeskske/.cache/pypoetry/virtualenvs/governanceplatform-AGxECetm-py3.10/lib/python3.10/site-packages/odf',
 '/home/helpdeskske/.cache/pypoetry/virtualenvs/governanceplatform-AGxECetm-py3.10/lib/python3.10/site-packages/odf',
 '/home/helpdeskske/.cache/pypoetry/virtualenvs/governanceplatform-AGxECetm-py3.10/lib/python3.10/site-packages/odf']
Server time:	Wed, 20 Mar 2024 10:37:39 +0000

**Comment by jerolomb** [comment]
No modification has been done on your server

When a new release will be ready we will let you know

**Comment by tochinet** [comment]
Strange, it worked before. Any idea of what could cause that kind of error, and/or how to correct it ?
If needed, I could delete some records if it helps, but right now, I don't understand the cause. But then this is unrelated to this issue. Should I migrate/create another one ?

**Comment by jerolomb** [comment]
ok we keep the possibility for regulator admin
