### ISSUE TITLE
Date field in form -> put a tooltip to explain date format

### ISSUE THREAD

**Issue by jerolomb** [informed-governance-project/NISINP#143]
put a tooltip to explain date format

**Comment by tochinet** [comment]
Actually, The point is that there is an icon to select a date, but then the time has to be edited manually, and the focus is buggy: 
- The notification date/time is not editable, but it has the icon. TODO remove it, add "/time"
- The detection date is editable, but when we click on the icon, we get a monthly calendar. Ok till there.
- Click on a date does update the field, but should close the monthly calendar popup.  You need to "click elsewhere". WRONG
- When editing the time, using backspace works as expected, but "delete" clear the whole field. WRONG
- Add another icon to select hour and minutes
- Remove second everywhere, meaningless
