### ISSUE TITLE
Translation missing

### ISSUE THREAD

**Issue by tochinet** [informed-governance-project/NISINP#150]
**Describe the bug**
In several pages, the translations are incomplete.

**To Reproduce**
1. Log in as Platform admin
2. Go to 'CERTs'  : /admin/governanceplatform/cert/
3. Click on 'FR', only half of page is translated
4. FULL NAME -> NOM COMPLET -> VOLLEDIGE NAAM
5. RECEIVE ALL INCIDENT (should be INCIDENTS) -> RECOIT TOUS LES INCIDENTS -> ALLE INCIDENTEN KRIJGEN
6. "L'objet CERT à modifier " should  be "le CERT" à modifier 
7. NL "DESCRIPTION" -> "BESCHRIJVING"

Idem in cert/add :
Full name: -> Nom complet -> Volledige naam :
Country -> Pays -> Land
Address -> Adresse -> Adres
Adresse e-mail pour notification -> Email adres voor notificatie

CERT USERS garder en  anglais ?  UTILISATEUR / GEBRUIKER (ou USER en NL)
IS ADMINISTRATOR -> ADMINISTRATEUR 
"object CERT user" -> utilisateur CERT

Idem https://incidents-test.ibpt.be/admin/governanceplatform/regulation/
"l'objet regulation" -> la régulation -> regulatie
"7 regulations" -> 7 régulations

Comme déjà signaler, la fonctionnalityé est celle d'un observateur/observer/waarnemer , l'usage de "CERT" a d'autres connotations. Un Search/Replace global serait bienvenu (0.3.0 ?)

**Expected behavior**
Everything should be in French resp. Dutch
Some of the above are already in https://github.com/informed-governance-project/NISINP/blob/master/locale/fr/LC_MESSAGES/django.po but it doesn't work. Maybe some capitalization issue ?

**Comment by tochinet** [comment]
Back to the issue list, the word "watcher" was selected to replace CERT (not "observer"). Obviously OK for me.

**Comment by cedricbonhomme** [comment]
> Some of the above are already in https://github.com/informed-governance-project/NISINP/blob/master/locale/fr/LC_MESSAGES/django.po but it doesn't work. Maybe some capitalization issue ?

I think that your instance is not running the very last version of the software. So you do not have the last translations updated. We will update it soon.

**Comment by tochinet** [comment]
Refaisant une passe sur l'instance monarc.lu : les onglets régulations et régulateurs ne sont pas correctement traduits
- en eux-même : pour les "sites" (EN et FR), NL est "Websites", donc c'est traduisible, mais au dessus rien n'est traduit : "SERIMA PLATFORM" ne devient pas "PLATEFORME SERIMA", CERTs, Regulations (pas de 'é') Regulators, Sectors, Users n'existent qu'en anglais.
- Dans la barre de navigation, NL "Voorpagina" veut dire couverture/1ere page, "Startpagina" est mieux (ou Homepage)
- Regulations - régulations - verordening
- Regulators - Régulateur(s) - Regulateur(s)
- Sector - Secteur - Sector(en)
- Users - Utilisateurs - Gebruikers  (Phone Number à traduire : Téléphone / Telefoon), CERT et Role (Rôle/Rol) au singulier! 

Dans la page incidents (FR/NL) presque rien n'est traduit (uniquement Administration/Beheer. Nécessité de "Reported Incidents", "Filters/Filtres/Filters" et tout le formulaires sauf "contains/contient/bevat" et "Search/Rechercher/Zoeken", les en-têtes, etc.

Idem menu déroulant profil : on a "mot de passe/wachtwoord", mais le reste est en anglais (dark theme etc.)

On peut continuer dans  les pages du regultorAdmin : ("Return to User website" qui devrait être "Back to incidents/Retour aux incidents/Terug naar incidenten")

Email Templates/Modèle d'e-mail/e-mail sjabloon
- On ne peut sélectionner un des modèles qu'en cliquant sur le premier chant soit ... "Creator Name" (Creator/Créateur/Maker) + Name/Nom/Naam Subject/Sujet/Onderwerp Content/Contenu/Inhoud
- Idem pour les autres, à noter que "Companies" (EN) devrait être "Operators/Opérateurs/Operatoren")

**Comment by tochinet** [comment]
Many improvements in the version 0.2.5, however, there are still inconsistencies with the language usage : 
- In the left column that lists the different screens, only the "Competent Authorities" is correctly translated when using another language UI. "sites" may be OK for the 4 languages, but "observer", 'regulations" and "users" are never translated. 
- English is also always used in the title and button (add user / Ajout de user / user toevoegen / user hinzufügen.

**Comment by jerolomb** [comment]
change : 

Not submitted and deadline exceeded à   remplacer par Report not submitted and submission deadline exceeded NOK
--
Submitted, but review not yet completed à   remplacer par Report submitted but review not yet completed NOK

**Comment by jfrocha** [comment]
Duplicated with issue https://github.com/informed-governance-project/NISINP/issues/247
