### ISSUE TITLE
Editing a RegulatorAdmin changes it into an OperatorAdmin (or User)

### ISSUE THREAD

**Issue by tochinet** [informed-governance-project/NISINP#169]
**Describe the bug**
**To Reproduce**
1. Log in as RegulatorAdmin
2. Create a User as RegulatorAdmin
3. Save. 
4. Click on first name
5. The shown window allows to modify first/last name, email and telephone. But below that, it also allows to select a "Compagnie" (should be "Entité", Sector, tick personnel de contact/admin, and show an empty column delete.

**Expected behavior**
It should be possible to edit a regulatorAdmin without demoting it.

**Comment by jfrocha** [comment]
Fixed @https://github.com/informed-governance-project/NISINP/commit/6c518261b931e6bae3ceba3c66f13e331e39b4b7
