### ISSUE TITLE
Regulator Admin can modify (very easily) the incident reference

### ISSUE THREAD

**Issue by tochinet** [informed-governance-project/NISINP#170]
**Describe the bug**
When looking at the incident list, the second column (Reference) is an editable field. Anything regulator admin types is automatically saves (But not in all situations : When field loses focus ?Needs Enter ? Tab to next field ?) without any warning. 

**To Reproduce**
1. login as regulator admin
2. Click on a "Reference" field 
3. Type something
4. See error. 

**Expected behavior**
This fields should not be editable.

**Screenshots**
![2024-09-03 11_01_59-Incidents](https://github.com/user-attachments/assets/71953520-d0c7-41c6-bbbc-7f30766a1b0c)

**Comment by jerolomb** [comment]
@PBD-ILR-LU are you agree to deactivate the reference field ?
