### ISSUE TITLE
[Req_36][Req_42]Incident forward

### ISSUE THREAD

**Issue by jfrocha** [informed-governance-project/NISINP#179]
- 	Logic used for the forward of incident notifications to the observer. E.g. in Luxembourg: 
- 	CIRCL : NIS2 AND private AND NOT critical infrastructure
- 	GovCERT : [NIS2 AND (PUBLIC OR (private AND critical infrastructure))] OR CER

La transmission des incidents aux observateurs doit être configurée régulation par régulation.
Il existe des autorités devant recevoir tous les incidents en lien avec une régulation. Par exemple au Luxembourg le HCPN (observer) devra recevoir tous les incidents de la NIS2 dans le cadre de son rôle de Single Point of Contact.
De plus, conformément au Req36, les 2 CERT du Luxembourg recevront en tant qu'observateur les incidents de la NIS2 filtrés en fonction du fait que l'entité est publique ou privée et du fait qu'une infrastructure critique est concernée ou pas.

Ainsi, quand le PlatformAdmin configure un observateur, il devrait pouvoir configurer régulation par régulation :
-	Si l’observateur reçoit toutes les notifications de cette régulation (single point of contact)
-	Si l’observateur reçoit une partie des notifications de cette régulation sur base d’une logique prédéfinie (CERT du Luxembourg)

**Comment by jfrocha** [comment]
@PBD-ILR-LU:
Can you clarify please, how the companies will be categorized?

In req_32, there are two approaches: 
1. Entity type (old essentials services meaning)
2. Entity category (critique, essential, important)

In req 36, there is a new categorization:
Public, private, critical infrastructure, anything else ?

**Comment by PBD-ILR-LU** [comment]
Hi Juan,

Thanks for your message.

Here are my answers:


  1.  Entity type
The entity types are defined in the attached directive in the annexes 1 and 2.
We simply need to simplify a bit the text. For example, the first entity type is “Electricity undertakings as defined in Article 2, point (57), of Directive (EU) 2019/944 of the European Parliament and of the Coun[1]cil (1), which carry out the function of ‘supply’ as defined in Article 2, point (12), of that Directive”. We could simply use “Electricity supplier”.


  1.  Entity category
There are various entity categories depending on the regulation:
NIS2 : essential entity; important entity ; none.
CER : operator of critical infrastructure: Yes/No
Public entity; Private entity.

Thanks

Best regards,

Pascal BERTRAND
SERVICE NISS

INSTITUT LUXEMBOURGEOIS DE RÉGULATION
17, rue du Fossé
L-2922 LUXEMBOURG
www.ilr.lu<http://www.ilr.lu>

T +352 28228 383
F +352 28228 229
***@***.******@***.***>


The information contained in this communication is confidential and may be legally privileged. It is intended solely for the use of the individual or entity to whom it is addressed and others authorised to receive it. If you are not the intended recipient you are hereby notified that any disclosure, copying, distribution or taking any action in reliance of the contents of this information is strictly prohibited and may be unlawful. The sender is neither liable for the proper nor complete transmission of the information contained in this communication nor for any delay in its receipt.
