### ISSUE TITLE
Home/Login page doesn't indicate correct version

### ISSUE THREAD

**Issue by tochinet** [informed-governance-project/NISINP#180]
**Describe the bug**
In the https://incidents.doamin.com/about/ and https://incidents.domain.com/account/login, there is an indication of the software version. This version is incorrect. It should be automatically retrieved from the software itself. 

**To Reproduce**
1. Go to 'account/login' or 'about page'
2. The links refer t an older version
3. Clicking on the version correctly ? sends to the version on the page, not the one of the installed software

**Expected behavior**
In order to avoid this issue in the future, the software version (and pPython version in the about page) should be automatically retrieved from the software itself, and not hard coded in the webpage

**Comment by jerolomb** [comment]
Hey, can we have what are the infos you see ? 

Because it's definitely not hardcoded

**Comment by tochinet** [comment]
Sure. Here is printscreen. It says 0.2.0 while we actually have 0.2.5
![2024-09-13 16_13_33-Connection](https://github.com/user-attachments/assets/07d90f4f-8b37-4cd5-a1a8-43f43b97c2b1)
