### ISSUE TITLE
Report log for regulator 

### ISSUE THREAD

**Issue by jerolomb** [informed-governance-project/NISINP#184]
**Describe the bug**

> Le régulateur en cliquant sur l'horloge ne voit que l'un des rapports NOK L'autre rapport est accessible en cliquant directement sur le nom du rapport.

> 
> Le regulator admin lui ne voit que 2 des 3 rapports en cliquant sur la montre. Ce comportement n'est pas consistant avec celui chez l'opérateur NOK
> La dernière version est accessible en cliquant sur le rapport lui-même. Néanmoins, pour éviter toute erreur il serait bon de lister quand on clique sur la montre toutes les versions des rapports. À défaut, un régulateur risquerait de cliquer sur le rapport du 11/09 de 9h01 en croyant que c'est le dernier.

**Comment by jerolomb** [comment]
c'est normal pour l'opérateur il s'agit bien d'un historique qui apparait donc dans l'historique.

Pour le régulateur c'est sa version actuelle de travail et non pas un historique. Voici la raison.

Pour moi le changement induirait une incohérence

@PBD-ILR-LU  valides-tu tout de même la modification ?

**Comment by PBD-ILR-LU** [comment]
Je comprends la logique implémentée.
Il me semblerait plus intuitif pour le régulateur de voir, en cliquant sur l’horloge, toutes les versions. Ceci évitera des questions.
Il s’agit d’une amélioration.
