### ISSUE TITLE
Lost data translations when clicking in save and continue tabs

### ISSUE THREAD

**Issue by jfrocha** [informed-governance-project/NISINP#229]
When filling the e-mail content in the various languages, the text disappears after clicking on "Save and continue editing", whereas I have a change confirmation at the top of the page.

**Comment by jerolomb** [comment]
Actually the framework by default doesn't allow to save all the 4 languages in one click, we have had a message to explain it has to be save language by language

**Comment by jerolomb** [comment]
Issue it's still here 
Workflow to reproduce : 
- Create an email template and click save and continue editing 

![image](https://github.com/user-attachments/assets/0ff4fe90-91ec-4c26-bd5b-ed5546fdc56d)

we get the green message, click the second language, click on save and continue editing we get the message but the value disappear : 
![image](https://github.com/user-attachments/assets/78121cf1-3618-4290-8747-a80243101ea2)

But it's correctly recorded in the DB 
![image](https://github.com/user-attachments/assets/8ce3db1b-4d8e-4341-86e4-ed6d82f58546)
