### ISSUE TITLE
System - Add a configurable session timeout

### ISSUE THREAD

**Issue by jerolomb** [informed-governance-project/NISINP#26]
**Describe the bug**
Add a configurable timeout, the default value is 30 minutes, each action on the platform should renew the timeslot.

Nice to have : have a pop up who prevent 5 minutes before the end of the session, and a click on it should renew the time slot

**Comment by jerolomb** [comment]
Configurable by sysadmin

**Comment by ruslanbaidan** [comment]
Based on this https://pypi.org/project/django-session-timeout/, seems only needed to add the default value in the config.py, for now dev:
https://github.com/informed-governance-project/NISINP/blob/master/governanceplatform/config_dev.py#L84
