### ISSUE TITLE
Make link to MONARC instance not mandatory

### ISSUE THREAD

**Issue by jerolomb** [informed-governance-project/NISINP#33]
**Describe the bug**
Make link to MONARC instance not mandatory

**Comment by ruslanbaidan** [comment]
There are 2 cases:
- operator monarc_path - not mandatory field;
- regulator monarc_path - could be a list of access URLs (e.g. multiple FO and BO).
  The other solution is to link the access list to the regulator users directly (access per regulator user).
  
**Solution**
Introduce a `resource_access` table linked as many2many with users with the following fields:
`id, type (monarc, security objectives, monitoring etc), url, access (type of access - read only, rwd)`

**Comment by jerolomb** [comment]
> There are 2 cases:
> 
>     * operator monarc_path - not mandatory field;
> 
>     * regulator monarc_path - could be a list of access URLs (e.g. multiple FO and BO).
>       The other solution is to link the access list to the regulator users directly (access per regulator user).
> 
> 
> **Solution** Introduce a `resource_access` table linked as many2many with users with the following fields: `id, type (monarc, security objectives, monitoring etc), url, access (type of access - read only, rwd)`

should not be linked to user but to companies/regulators

Not needed for the moment
