### ISSUE TITLE
Change user company type

### ISSUE THREAD

**Issue by jerolomb** [informed-governance-project/NISINP#37]
**Describe the bug**
Make user have one regulator OR (exclusive) many companies

**Comment by jfrocha** [comment]
Fixed in [faa0cbbe](https://github.com/informed-governance-project/governance-platform/commit/51cafea655972794c550fd3287f1af62faa0cbbe#diff-4481d393c10806a2dbebb692abb98d809dc297bca83de4ab31ed1405607875f5R564)
