### ISSUE TITLE
Multiple database management

### ISSUE THREAD

**Issue by jerolomb** [informed-governance-project/NISINP#6]
**Describe the bug**
Actually the multiple database management is not take into account, everything is written in the default database specified in the configuration file

**Expected behavior**
Multiple DB management working, maybe see for router and mapping in the config file : 
```
DATABASE_ROUTERS = ['dbrouter']
DATABASE_APPS_MAPPING = {'incidents': 'incidents',
                        'governanceplatform':'governance'}
```

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by ruslanbaidan** [comment]
I would suggest to go with a single database solution as:
1. it simplifies join queries data selections as some tables are related (e.g. incidents_incident_affected_services and governanceplatform_services)
2. There is no database level roles management of application users and all the permissions are implemented on the app level.
3. App may work microseconds faster as has to keep a single standalone connection.

**Comment by jerolomb** [comment]
i think we can let the possibility to the users to do it if they want and provide the stuff but it's not an emergency

**Comment by jerolomb** [comment]
not needed anymore
