### ISSUE TITLE
Admin site -> deletion / edition of USER and COMPANIES

### ISSUE THREAD

**Issue by jerolomb** [informed-governance-project/NISINP#73]
**Describe the bug**
The deletion of user and companies should be possible following the role of the user to delete, and the role of the user who launch the delete. 

- to avoid issue i propose to only delete company without user ?

**Comment by tochinet** [comment]
Ca semble en effet acceptable comme règle.

**Comment by jerolomb** [comment]
a priori ça ne fonctionne pas, lorsque la suppression n est pas faite elle apparait dans l historique et un message de bonne confirmation est envoyé

**Comment by jerolomb** [comment]
work : regulatorAdmin can delete companies following the rule
