### ISSUE TITLE
Incident notification testing report

### ISSUE THREAD

**Issue by tachafe** [informed-governance-project/NISINP#8]
**After login to report an incident**
•	Add the link to the incident list, otherwise we must create a new incident to access the incident list. Will make future testing easier.

----------------------------------------------------------------
**In general**
•	Increase the size of text fields
•	Mark mandatory fields
----------------------------------------------------------------
**Impacted services:**
   • After saving, still be able to identify and see what has been checked as regulation and services affected
**Personal data breach:**
- We must not select yes and no, put a radio button in place of the check box.
**Estimated impact :**
• Day and time the incident was observed ==> No field for time
• Day and time the incident started ==> No fields for time
• No control between the two dates. “Day and time the incident started” must always be before “Day and time the incident was observed”
• Proposal to use the DD/MM/YYYY format for the date.
**Notification dispatching**
• When clicking on “Others”, we should have a field to add another competent authority.
• At the end of “Notification dispatching”, after we have clicked on “Save”, we move to a new page with the “Incident list” and then if we return to the previous page we lose the previously recorded information.
----------------------------------------------------------------

- Select country drop down list ==> Possibility of simplifying the search for a country to select?

**Comment by jerolomb** [comment]
Hello,

Thanks for the issue
- Point 1, ok we will change the entry point
- Point 2, ok for the size and mandatory field
- For the Yes and No question, is a modification to do in the admin panel
- Idem for the Day and time field for time
- For the logic between the date, we will try to do it

The notification dispatching is under refactoring. 

Yes if we go back to the previous page, the save is already done, So the data are in the database and not in the form  

We will improve for select country
