### ISSUE TITLE
Incident list -> add filtering on column

### ISSUE THREAD

**Issue by jerolomb** [informed-governance-project/NISINP#88]
**Describe the enhancement**
Dashboard filtering: it is now possible to order the elements of the dashboard. It would be important to have the possibility to filter the content of some columns. Indeed, with the time the number of incidents contained in the dashboard will increase and it is important for the user to select what to display. It should be possible to apply filters to multiple columns at the same time. E.g. I want to see any incident from 2023 impacting the energy sector, having a significative impact and not being closed.
make it possible for various columns at the same time.

**Comment by tochinet** [comment]
Add ILR-high priority please
