### ISSUE TITLE
Regulator administrator -> reorder the view

### ISSUE THREAD

**Issue by jerolomb** [informed-governance-project/NISINP#92]
**Describe the enhancement**
Administration activities should be ordered in the sequence necessary to configure a new regulation: 1) workflows 2) reports 3) Impact ?

**ILR** : provide the full correct order you want

**Comment by tochinet** [comment]
Le problème est que l'expérience utilisateur reste peu engageante, il est très compliqué pour un régulateur d'identifier la procédure à suivre pour créer un workflow lié à une régulation. 
La procédure à suivre devrait être documentée avec précision et les pages d'édition devraient contenir des liens directs vers l'étape suivante. 
2 exemples pour la fenêtre "admin/incidents/impact/xxx/change/" 
- Elle ne suit pas du tout la même philosophie de design que les autres pages en ce qui concerne les secteurs.
- Un bouton à côté de "save and continue editing" pourrait pointer vers la liste des workflows qui permettent  de le sélectionner.

La définition des questions est trop rébarbative, il faudrait permettre de créer des questions sur une seule page.

**Comment by jerolomb** [comment]
fine now with others improvment
