### ISSUE TITLE
Regulator -> review of incident -> impacts

### ISSUE THREAD

**Issue by jerolomb** [informed-governance-project/NISINP#95]
**Describe the bug**
In regulator when reviewing an incident, it seems that when an incident has no impacts, clicking on impact leads to error 500

**ILR** To check : Is it possible that the workflow has "impacts are needed" ticked and no impacts linked ?

**Comment by tochinet** [comment]
Normalement il doit en effet y avoir des impacts liés. S'il n'y en a pas, c'est en effet une erreur, mais il faut la traiter, par exemple avec un popup qui permet de corriger la situation.

De plus, la liste des impacts n'est pas visible dans la fenêtre des workflows. Il serait intéressant d'avoir une vue complète du worlflow incluant les impacts. Ceci éviterait la condition d'erreur.

Par exemple, il serait pratique d'avoir dans la fenêtre "https://serima.monarc.lu/admin/incidents/workflow/10/change/" un bouton/lien vers la sélection des impacts à côté de la case "Impacts are needed".
